### ISSUE TITLE
Make addData prompts work correctly

### ISSUE THREAD

**Issue by whats-a-pj** [whats-a-pj/SQL-Employee-Tracker#2]
error is:
/Users/pjrasmussen/bootcamp/Assignments/week-12/SQL-Employee-Tracker/index.js:214
if (answers.employeeAddQuestions === "Add Employee") {
**^**

**ReferenceError: answers is not defined**
    at addData (/Users/pjrasmussen/bootcamp/Assignments/week-12/SQL-Employee-Tracker/index.js:214:1)
    at /Users/pjrasmussen/bootcamp/Assignments/week-12/SQL-Employee-Tracker/index.js:206:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.0

**Comment by whats-a-pj** [comment]
changed **answers.employeeAddQuestions** into **answers.employeeTracker**, but it comes up with the same error, not sure if it is a scope issue or what- can't access the answers data or somethingggg- needs to be based on the homePage (employeeTracker) questions
